apiVersion: v1
kind: Template
metadata:
  name: kafkanetes-deploy-kafka-novolume-1
  annotations:
    description: 1-pod Kafka
    tags: messaging,kafka

parameters:
- name: OBJECT_NAME_PREFIX
  description: Name prefix for each object created
  required: true
  value: kafkanetes-kafka
- name: ZOOKEEPER_SERVICE
  description: DNS name of ZooKeeper service
  required: true
  value: kafkanetes-zk
- name: IMAGESTREAM
  description: Kafkanetes imagestream name
  required: true
  value: kafkanetes

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${OBJECT_NAME_PREFIX}
    template:
      metadata:
        labels:
          deploymentconfig: ${OBJECT_NAME_PREFIX}
      spec:
        containers:
        - name: kafkanetes
          image: ${IMAGESTREAM}
          command:
          - bin/kafka-start.sh
          args:
          - ${OBJECT_NAME_PREFIX}
          - ${ZOOKEEPER_SERVICE}
          ports:
          - containerPort: 9092
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: false
        containerNames:
        - kafkanetes
        from:
          kind: ImageStream
          name: ${IMAGESTREAM}

- apiVersion: v1
  kind: Service
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    ports:
    - port: 9092
    selector:
      deploymentconfig: ${OBJECT_NAME_PREFIX}
